name: Build for Windows (JVM)

on:
  workflow_dispatch: # Cho phép bấm nút chạy thủ công

jobs:
  build:
    runs-on: windows-latest # Chạy trên máy chủ Windows của GitHub

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: git update-index --chmod=+x gradlew

      - name: Build with Gradle
        run: ./gradlew installDist

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: game2048-windows-jvm
          path: build/install/game2048/
