name: Build Windows App

on:
  workflow_dispatch: 

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'
          cache: 'gradle'

      - name: Build with Gradle
        # Sử dụng task này để tạo ra bộ file thực thi đầy đủ
        run: ./gradlew jvmInstallDist --no-daemon

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: game2048-windows-dist
          # Đường dẫn chuẩn sau khi build jvmInstallDist
          path: build/install/game2048/
