name: Build for Windows (JVM)

on:
  workflow_dispatch: 

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21  # Nâng cấp từ 17 lên 21
        uses: actions/setup-java@v4
        with:
          java-version: '21' # Đây là dòng quan trọng nhất
          distribution: 'zulu'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: git update-index --chmod=+x gradlew

      - name: Build with Gradle
        run: ./gradlew installDist

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: game2048-windows-jvm
          path: build/install/game2048/
